# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Graha Aquaponik
email: info@grahaaquaponik.com
description: > # this means to ignore newlines until "baseurl:"
  "Tidaklah seorang muslim menanam suatu pohon melainkan apa yang dimakan dari tanaman itu sebagai sedekah baginya, dan apa yang dicuri dari tanaman tersebut sebagai sedekah baginya dan tidaklah kepunyaan seorang itu dikurangi melainkan menjadi sedekah baginya." (HR. Imam Muslim Hadits no.1552)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://grahaaquaponik" # the base hostname & protocol for your site
twitter_username: grahaaquaponik
instagram_username:  grahaaquaponik
facebook_username: Graha Aquaponik

# Build settings
markdown: kramdown
